### ISSUE TITLE
请教一下，公钥文件和公钥对象的转换问题

### ISSUE THREAD

**Issue by mr-tan4** [ZZMarquis/gmhelper#10]
我在对公钥进行写入写出是出现了问题，我采用der方式将公钥写出到文件，但是从公钥文件转换为公钥对象时出现了问题，
这是java抛出的异常：
> `java.io.IOException: Sender's public key has invalid point encoding 0x30`

**Comment by ZZMarquis** [comment]
参考BCECUtil工具类里的convertECPublicKeyToX509和convertX509ToECPublicKey方法，公钥转成字节流最好是专程DER编码的X509标准的字节流。

**Comment by mr-tan4** [comment]
ok,谢谢
