### ISSUE TITLE
怎样在使用同一个私钥的情况下，生成多套公钥

### ISSUE THREAD

**Issue by little06** [ZZMarquis/gmhelper#11]
看到代码里的BCECUtil.java 有个方法  public static ECPublicKeyParameters createECPublicKeyParameters(BigInteger x, BigInteger y,
        ECCurve curve, ECDomainParameters domainParameters) 
没有相关的说明，能指导一下这个方法怎么用的吗？

**Comment by ZZMarquis** [comment]
因为SM2的加解密、签名验签需要使用ECPublicKeyParameters实例，而有的时候交换公钥又只是交换公钥的XY分量，这个方法就是使用XY分量构造一个ECPublicKeyParameters实例出来。
