### ISSUE TITLE
使用此软件算法验签时出现高概率的失败，但是也有一半成功

### ISSUE THREAD

**Issue by liangliang-12** [ZZMarquis/gmhelper#14]

**Comment by ZZMarquis** [comment]
你是用什么签名的？

**Comment by ZZMarquis** [comment]
失败时的签名和公钥能发上来看一下吗？

**Comment by ZZMarquis** [comment]
一半成功一半失败，我猜是不是你们的签名DER编码时没有注意大数的补零呢？这样就有一定的概率导致DER编码的签名结果是不对的。

**Comment by ZZMarquis** [comment]
SM2签名DER编码后可能是70/71/72个字节，分别对应不需要补零、R或S其中之一补零，RS都补零。如果你们的签名结果一直都是70/71/72中的固定一种情况，那么就可能是你们的签名编码有问题。

**Comment by liangliang-12** [comment]
公钥证书中包含企业信息，不方便发这里，加签用的硬件，软件验签不过，但是硬件可以把这个不过的签名值验过

**Comment by liangliang-12** [comment]
也不是一半概率，大概5%左右吧

**Comment by ZZMarquis** [comment]
找不到这个微信号。发我邮箱吧，在我的个人简介里有。
