### ISSUE TITLE
sm2私钥转PKCS8格式String

### ISSUE THREAD

**Issue by GoldSaintEagle** [ZZMarquis/gmhelper#15]
SM2PublicKey类中重载了getEncoded方法，可以将sm2公钥转换成PKCS8格式String；但是没有SM2PrivateKey类的实现。因此，sm2私钥转换成PKCS8格式String的方法采用了BCECPrivateKey。

但是，生成的私钥包含了sm2椭圆曲线的各个参数（N、P），而并没有采用oid替换，如下：

3082024b0201003081ec06072a8648ce3d02013081e0020101302c06072a8648ce3d0101022100fffffffeffffffffffffffffffffffffffffffff00000000ffffffffffffffff30440420fffffffeffffffffffffffffffffffffffffffff00000000fffffffffffffffc042028e9fa9e9d9f5e344d5a9e4bcf6509a7f39789f515ab8f92ddbcbd414d940e9304410432c4ae2c1f1981195f9904466a39c9948fe30bbff2660be1715a4589334c74c7bc3736a2f4f6779c59bdcee36b692153d0a9877cc62a474002df32e52139f0a0022100fffffffeffffffffffffffffffffffff7203df6b21c6052b53bbf40939d5412302010104820155308201510201010420d03cd038670fce6e2cdd7e44aef15b171f53233488080f724e35958da2a416dfa081e33081e0020101302c06072a8648ce3d0101022100fffffffeffffffffffffffffffffffffffffffff00000000ffffffffffffffff30440420fffffffeffffffffffffffffffffffffffffffff00000000fffffffffffffffc042028e9fa9e9d9f5e344d5a9e4bcf6509a7f39789f515ab8f92ddbcbd414d940e9304410432c4ae2c1f1981195f9904466a39c9948fe30bbff2660be1715a4589334c74c7bc3736a2f4f6779c59bdcee36b692153d0a9877cc62a474002df32e52139f0a0022100fffffffeffffffffffffffffffffffff7203df6b21c6052b53bbf40939d54123020101a14403420004d774c76f9fce4735244b620f0e139373ba34e837225f818da92483c3b896ca0501fac506290b1a4b09f3e79451259cd81a2775a2c85284782690ec0feb7e5f04

我希望生成比较简洁的PKCS8格式，类似于SM2PublicKey的getEncoded方法。期望的结果如：

308187020100301306072a811ccf55020106082a811ccf5501822d046d306b02
01010420a43436cec5ffbbf897897fbec860053de978086eb99fd67dcdd4817d
949e83eba144034200048860af05a1a67f5e48df9286625618f6eb58b02f41d0
0c5b60981ef96dbfc0b3f469cd4facc0746e58e2bef993869a361fd9a90c246e
44fede35d19fae135cb9

**请问是否可以提供_SM2PrivateKey_的_getEncoded_方法？**

备注：

- [ASN1 decode](https://lapo.it/asn1js/)
- 生成PKCS8 Hex string 代码；

`KeyPair keyPair = SM2Util.generateBCECKeyPair();
BCECPrivateKey smPriv = new BCECPrivateKey(keyPair.getPrivate().getAlgorithm(), (BCECPrivateKey) keyPair.getPrivate());
String privHexString = Hex.encodeHexString(smPriv.getEncoded());

SM2PublicKey smPub = new SM2PublicKey(keyPair.getPublic().getAlgorithm(), (BCECPublicKey) keyPair.getPublic());
String pubHexString = Hex.encodeHexString(smPub.getEncoded());`

**Comment by ZZMarquis** [comment]
有了

**Comment by GoldSaintEagle** [comment]
So efficient!
