### ISSUE TITLE
跨语言使用的问题

### ISSUE THREAD

**Issue by shijl80** [ZZMarquis/gmhelper#17]
SM2算法生成公私钥对长度会变化：
AsymmetricCipherKeyPair keyPair = SM2Util.generateKeyPairParameter();
ECPrivateKeyParameters priKey = (ECPrivateKeyParameters) keyPair.getPrivate();
ECPublicKeyParameters pubKey = (ECPublicKeyParameters) keyPair.getPublic();
System.out.println("priKey len=" + priKey.getD().toByteArray().length);
System.out.println("pubKey len=" + pubKey.getQ().getEncoded(false).length);
私钥长度有时是32，有时是33。
公钥长度是65。
而C语言那边私钥是固定的32位，公钥是2个32位。
请问如何与C那边对应上？

**Comment by ZZMarquis** [comment]
这是大数的补0规则导致的，如果大数的第一个比特位是1的话会在前面补一个0x00字节。
SM2Util.getRawPrivateKey这个方法你可以看一下

**Comment by shijl80** [comment]
谢谢！看到了，这个问题解决了。
不过还有个问题，C那边SM2签名后是固定64位，而这里SM2签名数据的长度根据密钥对会变化，可能值有70、71、72位，这个又要如何与C那边对应呢？

**Comment by ZZMarquis** [comment]
这边的签名结果是DER编码的，长度不固定也是大数补0导致的，R和S都需要补0就会是72位、都不补0就是70位，其中一个补0就是71位。
SM2Util.decodeDERSM2Sign方法可以看一下

**Comment by shijl80** [comment]
还是不行，只取32字节私钥和64字节公钥，转换回来后，代码不变，签名和验签一会成功，一会失败。
代码如下：

SM2Util：
public static ECPrivateKeyParameters createECPrivateKeyParameters(byte[] rawPrivateKey) {
        return  BCECUtil.createECPrivateKeyParameters(new BigInteger(rawPrivateKey), DOMAIN_PARAMS);
    }
public static ECPublicKeyParameters createECPublicKeyParameters(byte[] rawPublicKey) {
        byte[] x = new byte[32];
        byte[] y = new byte[32];
        System.arraycopy(rawPublicKey,0,x,0,32);
        System.arraycopy(rawPublicKey,32,y,0,32);
        return BCECUtil.createECPublicKeyParameters(x, y, CURVE, DOMAIN_PARAMS);
    }

SM2UtilTest.testSignAndVerify()：
            KeyPair keyPair = SM2Util.generateKeyPair();
            byte[] priBytes = SM2Util.getRawPrivateKey((BCECPrivateKey) keyPair.getPrivate());
            byte[] pubBytes = SM2Util.getRawPublicKey((BCECPublicKey) keyPair.getPublic());
            ECPrivateKeyParameters privateKeyParameters = SM2Util.createECPrivateKeyParameters(priBytes);
            ECPublicKeyParameters publicKeyParameters = SM2Util.createECPublicKeyParameters(pubBytes);
            byte[] data = "12345678".getBytes();
            byte[] signBytes = SM2Util.sign(privateKeyParameters, data);
            byte[] rawSignBytes = SM2Util.decodeDERSM2Sign(signBytes);
            signBytes = SM2Util.encodeSM2SignToDER(rawSignBytes);
            boolean vFlag = SM2Util.verify(publicKeyParameters, data, signBytes);
            System.out.println("vFlag=" + vFlag);

**Comment by shijl80** [comment]
发现应该是前面没有补0导致的，改成下面这样就好了：
public static ECPrivateKeyParameters createECPrivateKeyParameters(byte[] rawPrivateKey) {
        BigInteger d = new BigInteger(rawPrivateKey);
        if (rawPrivateKey[0]<0){
            byte[] b = new byte[rawPrivateKey.length+1];
            System.arraycopy(rawPrivateKey,0,b,1,rawPrivateKey.length);
            b[0] = 0;
            d = new BigInteger(b);
        }
        return BCECUtil.createECPrivateKeyParameters(d, DOMAIN_PARAMS);
    }

**Comment by ZZMarquis** [comment]
你不用那么写，new BigInteger(1, rawPrivateKey)就行了，强制把大数设为整数。

**Comment by shijl80** [comment]
:+1:
