### ISSUE TITLE
关于no such algorithm: SM4 for provider BC异常解决

### ISSUE THREAD

**Issue by CherryLv** [ZZMarquis/gmhelper#18]
如果遇到这个问题的朋友，不妨试试
if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) != null){
			double version = Security.getProvider(BouncyCastleProvider.PROVIDER_NAME).getVersion();
			Log.i("sys","原有version="+version);
		}
		Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME);
		if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null){
			Log.i("sys","运行环境没有BouncyCastleProvider");
			Security.addProvider(new BouncyCastleProvider());
		}
可能在应用启动的时候，已经有了一个低版本的BCprovider被自动add进当前系统，需要先移除再加入高版本的，我这边打印出来是1.57,1.57就是没有国密算法,1.58开始部分支持,1.59才较完善支持

**Comment by shijl80** [comment]
补充下，如果是安卓系统，会自带低版本BouncyCastle，需要使用Spongy Castle。

**Comment by EugeniaGao** [comment]
笔记：android上，打开混淆开关会出现这个问题，关闭就不会。所以需要在混淆规则里面添加-keep  class org.bouncycastle.**{*;} 不做混淆

**Comment by kuoyeDong** [comment]
> 

猜到了
