### ISSUE TITLE
关于解密使用openssl的SM2加密的密文无法解密的问题

### ISSUE THREAD

**Issue by DavidDXY** [ZZMarquis/gmhelper#22]
老哥你好，我使用老哥的库正常自己加解密都是OK的  我把秘钥以PEM文件方式发给linux设备，linux设备使用的是Openssl的加密库，但是无法解密，解析了openssl加密后的密文与本地加密的密文格式有差异：
![image](https://user-images.githubusercontent.com/28525559/59814486-0a39cf80-9348-11e9-821a-12e697d20745.png)

**Comment by DavidDXY** [comment]
使用老哥的库加密的密文经过der编码后的是：
![image](https://user-images.githubusercontent.com/28525559/59814524-31909c80-9348-11e9-8ccf-110310d7d254.png)

**Comment by DavidDXY** [comment]
请问是否与openssl配合老哥是否有经验？

**Comment by ZZMarquis** [comment]
这里SM2密文是按C1C3C2进行DER编码的，openssl的密文呢？

**Comment by DavidDXY** [comment]
> 这里SM2密文是按C1C3C2进行DER编码的，OpenSSL的的密文呢？

需要阅读以下OpenSSL的源码看一下，目前用老哥的库生成的秘钥Openssl可以使用，但是加密的密文编码后解密，报了大数异常 Invalid point coordinates

**Comment by DavidDXY** [comment]
上面我分析了用openssl加密的密文，发现Openssl库用老哥生成的公钥加密后DER编码前两个sequence里字节长度为33，用老哥的库加密后的编码密文的DER里前两个sequence里字节长度为32.

**Comment by DavidDXY** [comment]
看了下老哥的代码，这里C1x,C1y的长度来自曲线参数计算，int curveLength = BCECUtil.getCurveLength(DOMAIN_PARAMS);

**Comment by ZZMarquis** [comment]
c1x, c1y那里算出来的长度只是为了算数组拷贝的长度。当那32个字节塞到ASN1Integer里然后进行DER编码的时候，根据大数补0的规则是有可能编码成33个字节的（当第一个字节大于等于8，也就是第一个比特是1的时候，大数前面需要补0）

**Comment by ZZMarquis** [comment]
Openssl使用的曲线参数对吗？

**Comment by DavidDXY** [comment]
> Openssl使用的曲线参数对吗？

从openssl的源码来看
![image](https://user-images.githubusercontent.com/28525559/59906630-cc1dd800-943b-11e9-824f-a29329f87d04.png)
曲线用的也是SM2P256V1

**Comment by ZZMarquis** [comment]
那就不好说了，要不你试试你们那个跟gmssl能不能互相加解密

**Comment by DavidDXY** [comment]
> 那就不好说了，要不你试试你们那个跟gmssl能不能互相加解密

老哥能给我一下gmssl测试的例子么  邮箱103216270@qq.com,感激不尽

**Comment by ZZMarquis** [comment]
[GmSSL](https://github.com/guanzhi/GmSSL)
你可以参考它的测试代码

**Comment by Gsealy** [comment]
@DavidDXY BC按照最开始的英文版Sm2实现的，加解密拼接方式有问题[SM2Engine.java](
https://github.com/bcgit/bc-java/blob/master/core/src/main/j2me/org/bouncycastle/crypto/engines/SM2Engine.java#L46)

更新BC到最新版本就可以了
