### ISSUE TITLE
你好, BouncyCastleProvider是系统什么时候添加进去的

### ISSUE THREAD

**Issue by alibo001** [ZZMarquis/gmhelper#24]
你好,我在用SM4.
我的项目复制你相同的依赖, 但是Security.getProvider(BouncyCastleProvider.PROVIDER_NAME)是null ,连低版本的都没有. 需要手动Security.addProvider(new BouncyCastleProvider());
但是 在你的SM4Util里加了个main方法, 直接就能获取到. 
不知您清楚是为什么吗

**Comment by ZZMarquis** [comment]
SM4Util继承了GMBaseUtil，在这个父类里add了
