### ISSUE TITLE
关于国密 java双向认证通信的问题

### ISSUE THREAD

**Issue by sstsky** [ZZMarquis/gmhelper#25]
最近工作中遇到了使用国密证书进行java客户端ssl双向认证通信的需求，但是java目前不支持国密，一直卡在这里没有解决思路。看到您在的github上的开源项目，想着您在这块应该很有研究，所以想向您请教一下，或者有没有什么解决思路。

**Comment by ZZMarquis** [comment]
我以前用Apache的httpclient做过，印象中是可以通过实现SSLContext接口来实现自己的SSL认证逻辑。可以上网搜一下这方面相关的东西。

**Comment by sstsky** [comment]
嗯 是的 现在有个问题是java的KeyStore不支持国密的曲线算法
Caused by: java.io.IOException: Unknown named curve: 1.2.156.10197.1.301
这块难以解决，当时您是遇到过这个问题吗

**Comment by ZZMarquis** [comment]
我们是自己写的验证证书逻辑，没有用Java的keystore

**Comment by sstsky** [comment]
额 那估计这块的工作量要不小了 嗯 那您有相应的实现demo吗  如果不涉及安全的话 能借鉴一下吗

**Comment by ZZMarquis** [comment]
demo没有，那是属于老东家公司的代码了。其实工作量不大，我记得我们当时那块也就两三百来行代码吧。

**Comment by sstsky** [comment]
主要我对ssl证书验证这块理解还是皮毛，相应的学习成本加入进去，时间就长了

**Comment by sstsky** [comment]
你们当时没有用keystore是因为自己实现的X509TrustManager和X509KeyManager吗？

**Comment by ZZMarquis** [comment]
对自己实现Apache httpclient的x509trustmanager

**Comment by sstsky** [comment]
嗯 好的  我试一下 非常感谢

**Comment by point0mine** [comment]
@sstsky   重新实现X509TrustManager，你有尝试成功吗？我也遇到同样的问题

**Comment by sstsky** [comment]
> @sstsky 重新实现X509TrustManager，你有尝试成功吗？我也遇到同样的问题

嗯 没有 当时是和甲方沟通发现他们同样是软验签的方式进行加解密的后 就直接实现X509TrustManager绕过通信验证了

**Comment by point0mine** [comment]
你是跳过Java keystore直接实现X509TrustManager吧？是fabric-sdk-java吗？有没有示例代码参考一下，局部的就可以 @sstsky
