### ISSUE TITLE
你好，怎么往pfx证书中添加自定义扩展域

### ISSUE THREAD

**Issue by zhaodidada** [ZZMarquis/gmhelper#27]

**Comment by ZZMarquis** [comment]
你试一下PKCS12SafeBagBuilder类里的addBagAttribute方法

**Comment by xipki** [comment]
你是指证书的扩展域吗？

**Comment by zhaodidada** [comment]
> 你是指证书的扩展域吗？

是的，工作刚好有这个需求

**Comment by xipki** [comment]
你可以在生成证书时用X509v3CertificateBuilder.addExtension（）方法来添加。

**Comment by zhaodidada** [comment]
> 你可以在生成证书时用X509v3CertificateBuilder.addExtension（）方法来添加。

好的，多谢大哥，大哥你有有关证书的学习资料或者项目么，我想深入了解一下这块的知识。

**Comment by xipki** [comment]
学习资料我也不清楚，不过如果你有一定基础的话可以看看证书的标准RFC5280。

简单的证书系统这个项目做的不错。如果你想更深入的和生产环境中使用，可以考虑我的开源项目。

**Comment by zhaodidada** [comment]
> 学习资料我也不清楚，不过如果你有一定基础的话可以看看证书的标准RFC5280。
> 
> 简单的证书系统这个项目做的不错。如果你想更深入的和生产环境中使用，可以考虑我的开源项目。

好的，多谢，我会看看的。
