### ISSUE TITLE
你好,我正在研究国密加密算法,也是基于BC,想开源一个小型CA包,支持一般的证书签发,吊销,验证等流程,目前实现了rsa,ECDSA,dsa;sm2始终差一点,希望能和您交流交流,我刚开始做,对这个理论研究差点

### ISSUE THREAD

**Issue by dushitaoyuan** [ZZMarquis/gmhelper#3]
你好,我正在研究国密加密算法,也是基于BC,想开源一个小型CA包,支持一般的证书签发,吊销,验证等流程,目前实现了rsa,ECDSA,dsa;sm2始终差一点,希望能和您交流交流,我刚开始做,对这个理论研究差点;
最终想基于BC实现一个完整sm2provider,然后开源出来(支持,sm2cipher,sm4cipher,sm2digest,tls秘钥协商);
目前对于sm算法和实现途径有些迷茫,希望交流一下

**Comment by ZZMarquis** [comment]
好啊，有什么问题可以发到这里大家交流。或者可以把你微信号发到我邮箱，我加你微信。
