### ISSUE TITLE
SM4算法怎么才能支持32字节的密钥

### ISSUE THREAD

**Issue by bureos** [ZZMarquis/gmhelper#34]
测试的时候，SM4Util里的DEFAULT_KEY_SIZE 默认密钥长度是128位，也就是16个字节。测试没有问题。现在想的是，能不能支持256位32个字节，测试的时候报错了。部分堆栈如下：
org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$InvalidKeyOrParametersException: SM4 requires a 128 bit key
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1346)
	at javax.crypto.Cipher.init(Cipher.java:1282)
	at org.zz.gmhelper.SM4Util.generateCbcCipher(SM4Util.java:189)
	at org.zz.gmhelper.SM4Util.encrypt_Cbc_Padding(SM4Util.java:81)
	at demo.wodetest.TestSM4.testSM4EcbPKCS5(TestSM4.java:24)

**Comment by bureos** [comment]
public static final byte[] SRC_DATA_16B = new byte[]{1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8};    
    @Test
    public void testSM4EcbPKCS5() throws Exception{
    	
    	byte[] key = SM4Util.generateKey(256);
    	System.out.println("key.length:" + key.length);
        byte[] iv = SM4Util.generateKey(128);
        System.out.println("key:"+ByteUtils.toHexString(key));
        System.out.println("iv :"+ByteUtils.toHexString(iv));
        
    	byte[] cipherText = SM4Util.encrypt_Cbc_Padding(key, iv, SRC_DATA_16B);
        System.out.println("SM4 CBC Padding encrypt result:\n" + Arrays.toString(cipherText));
        byte[] decryptedData = SM4Util.decrypt_Cbc_Padding(key, iv, cipherText);
        System.out.println("SM4 CBC Padding decrypt result:\n" + Arrays.toString(decryptedData));
        
        if (!Arrays.equals(decryptedData, SRC_DATA_16B)) {
            Assert.fail();
        }
    	
    }

**Comment by ZZMarquis** [comment]
SM4算法不支持256的密钥，只支持128的。

**Comment by bureos** [comment]
好的 谢谢
