### ISSUE TITLE
SM2CertUtil报错

### ISSUE THREAD

**Issue by elliotliu** [ZZMarquis/gmhelper#36]
org/bouncycastle/bcprov-jdk15on/1.62/bcprov-jdk15on-1.62.jar has unsigned entries - org/bouncycastle/LICENSE.class

**Comment by elliotliu** [comment]
我从网上重新下载bcprov-jdk15on-1.62.jar替换后又报这个错unable to extract data: unable to create stream: unable to create InputDecryptor: Illegal key size or default parameters

**Comment by elliotliu** [comment]
![image](https://user-images.githubusercontent.com/16829950/70764126-8827e200-1d91-11ea-9d30-e47ba9a89e99.png)
1、maven下载的jar和网上下载的jar签名差别很大，用网上下载jar替换maven中的jar解决签名问题。
2、Illegal key size or default parameters是因为jdk出口策略限制，密码长度改为6为长度即可，或者替换jdk中的local_policy.jar和US_export_policy.jar两个jar。

**Comment by xipki** [comment]
1. bcprov都是由bouncycastle自己发布的，包括官网和maven的中心库，都是可以使用的。不要下载非官方的，有安全风险。
2.  最简单的办法就是用最新的jdk 8或者以上。不用另外安装jar包了。

**Comment by elliotliu** [comment]
1.从maven下载下来的会报签名不否；
2.有些项目还是采用的jdk7，升级风险太大。

**Comment by ZZMarquis** [comment]
Illegal key size or default parameters是加密算法出口限制导致的。直接用JDK1.8.0_162及以上版本不会有此问题。如果因为历史原因不能升级JDK版本，至需要替换local_policy.jar和US_export_policy.jar两个jar。以下是JDK1.6-1.8相应的local_policy.jar和US_export_policy.jar的下载地址：
JDK1.6的下载地址：
http://www.oracle.com/technetwork/java/javase/downloads/jce-6-download-429243.html
JDK1.7的下载地址：
http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html
JDK1.8的下载地址：
http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
