### ISSUE TITLE
其实…bc库已经实现了SM2、SM3、SM4的加解密

### ISSUE THREAD

**Issue by duanxinyuan** [ZZMarquis/gmhelper#37]
这么多代码…辛苦了

既然知道bc库已经实现了SM2、SM3、SM4的加解密，为什么不直接用jdk的Cipher呢

像SM2解密，可以这样：

Cipher cipher = Cipher.getInstance("SM2");
cipher.init(Cipher.DECRYPT_MODE, ecPrivateKey);
return cipher.doFinal(data);

SM3摘要算法和SM4对称加密算法，也是如此

**Comment by ZZMarquis** [comment]
SM2好像不能这么用，SM2不符合JCE规范。SM3/SM4可以。
这个项目就是简单的封装，这个项目本身并没有实现算法，都是对BC的调用组合，也可以当成一个sample看。

**Comment by duanxinyuan** [comment]
可以的，BC库里没有实现的只有ASN.1/DER编码，其他好像都是符合SM2规范的，但是实际Java项目中，用不到DER编码，DER编码应该更多在和openssl交互的时候用。

我一开始想借（抄）鉴（袭）的你的代码，但是发现BC库里EC实现有SM2。
我也去一些在线加密网站试了，是没问题的，
然后发现你的库的加解密效果和BC库的SM2实现的效果一样，可以互相加密解密

**Comment by ZZMarquis** [comment]
嗯，是一样的，这个项目本身就是基于BC库的。
