### ISSUE TITLE
相同类型转换失败

### ISSUE THREAD

**Issue by tianpeter** [ZZMarquis/gmhelper#40]
放到linux服务器上运行报错  jar包都有
org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey cannot be cast to org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey

请问这是为什么 ？

**Comment by ZZMarquis** [comment]
有详细的异常堆栈信息吗？这个错误有点怪呀，为啥完全相同的类型还会转换失败。。。

**Comment by tianpeter** [comment]
> 有详细的异常堆栈信息吗？这个错误有点怪呀，为啥完全相同的类型还会转换失败。。。
没 就是报上面那个错误 但是在本地运行就是没问题的 放到服务器上就出错 jdk都是1.7 
具体就是在调用 BCECutil.java    (BCECPrivateKey) kf.generatePrivate(peks);  这个方法报错了（应该是在277行）

**Comment by ZZMarquis** [comment]
信息太少，我也不好判断。JDK小版本是否一样？

**Comment by JustPlay1994** [comment]
感觉有点像这个问题：不同的类加载器加载同一个class文件，得到的类型也不相同（但是包名类名相同）。如果可以，试着把类加载器改为双亲委派模式看能不能解决。

**Comment by xipki** [comment]
检查一下class path是否有两个不同的bcprov-jdk15on*.jar文件。比如在tomcat下在lib目录下有一个，同时war里面也含了一个。

**Comment by yuanyp** [comment]
对应的js的有没有啊，网上找的js 搞出来不一样，无语了啊。

**Comment by ZZMarquis** [comment]
@yuanyp 我没做js的，可以再在github上找找，一般star较多的应该靠谱一点

**Comment by 550756709** [comment]
> > 有详细的异常堆栈信息吗？这个错误有点怪呀，为啥完全相同的类型还会转换失败。。。
> > 没 就是报上面那个错误 但是在本地运行就是没问题的 放到服务器上就出错 jdk都是1.7
> > 具体就是在调用 BCECutil.java    (BCECPrivateKey) kf.generatePrivate(peks);  这个方法报错了（应该是在277行）

请问下楼主 这个问题解决了嘛
