### ISSUE TITLE
咨询个问题

### ISSUE THREAD

**Issue by lxmlianyi** [ZZMarquis/gmhelper#43]
本地没事，部署到环境 就报这个错java.security.NoSuchAlgorithmException: No such algorithm: SM4/ECB/PKCS5Padding，
帮忙看看是啥原因吧，微信号15763605318，谢谢

**Comment by ZZMarquis** [comment]
1、看下有没有加载BouncyCastleProvider：
``Security.addProvider(new` BouncyCastleProvider());`
2、看下是不是jar包冲突，是否同时引入了高版本和低版本的bc库。

**Comment by lxmlianyi** [comment]
谢谢，这两个情况都不存在，可能是我们linux环境，或者weblogic的问题，

**Comment by ZZMarquis** [comment]
可以看下加载的BC的版本，是不是weblogic本身带了低版本的BC？
