### ISSUE TITLE
大佬，国密sm2 这个这个私钥能转成公钥吗，有这个api吗

### ISSUE THREAD

**Issue by WhiteCjy** [ZZMarquis/gmhelper#44]

**Comment by ZZMarquis** [comment]
新加了点代码，加上了这个API，可以pull下代码。BCECUtil.buildECPublicKeyByPrivateKey

**Comment by WhiteCjy** [comment]
> 新加了点代码，加上了这个API，可以pull下代码。BCECUtil.buildECPublicKeyByPrivateKey

好滴，感谢！还可以请教下你 国密算法里 能否把私钥转成助记词，然后2者间能否互转啊

**Comment by ZZMarquis** [comment]
可以是可以，你可以找一个你易记的字符串，SHA256或者SM3成32个字节来做私钥。但是这样不好，私钥最好还是要用一个随机性良好的随机数。
