### ISSUE TITLE
这个国密根据私钥转出来的公钥和js版sm-crypto 国密库 私转公 得到的结果不一样？作者能看看吗

### ISSUE THREAD

**Issue by WhiteCjy** [ZZMarquis/gmhelper#46]
用的以太坊 私钥来转 
js版
私:0xc4db720f5e6ceb7b476cf17e36379efbf27fe6da20ab631d7aedc5ff1173c666
公:04bf7c85d72e61d4ca4f1112c4a127ba1936deda4be48b7cf6bc9dd9f9a40c7f138d21da85f46f8eefd5028f2ae2ccbe8b830662e242e121d013a624b765b314b4

java国密
私:0xc4db720f5e6ceb7b476cf17e36379efbf27fe6da20ab631d7aedc5ff1173c666
公:0415a74aa52cb303e5bbeeb7c78559b47e17476eecaa2e5490a78773e563d138a1f3f5a55db28b24c5f1250e1d7ef69a6bd7da5bc900add4d71c20889407eb6aee

**Comment by ZZMarquis** [comment]
单纯从数据上看不出来哪个有问题。不过，js版的那对公私钥在BC上进行签名验签验不过。不知道它用的曲线是不是国密推荐的曲线。
