### ISSUE TITLE
您好，请问下这个可以和前端的加解密工具sm-crypto通用吗

### ISSUE THREAD

**Issue by huahua315148** [ZZMarquis/gmhelper#47]
您好，请问下这个可以和前端的加解密工具sm-crypto通用吗，sm2验签那面

**Comment by ZZMarquis** [comment]
这个不是很清楚，我没用过sm-crypto。不过之前有个兄弟反映可能是有点问题，你们可以交流下。
这个issue：#46

**Comment by huahua315148** [comment]
那可以问下你们前端是用的那个js算法吗，不胜感激

**Comment by ZZMarquis** [comment]
我们当时做国密相关的项目时没有Web前端😂所以我不知道js哪个国密算法库靠谱

**Comment by SkyGrass** [comment]
我是对着 sm-crypto 的签名与验签 重新写了个 C# 的。
