### ISSUE TITLE
你好，我想问下bcprov-jdk15和bcprov-jdk15on这两个jar有什么区别

### ISSUE THREAD

**Issue by scchenhao** [ZZMarquis/gmhelper#5]
项目里面引用了这两个jar报冲突。

**Comment by ZZMarquis** [comment]
bcprov-jdk15on表示支持JDK1.5~JDK1.8
bcprov-jdk15我没用过。。。
[BC官网](http://www.bouncycastle.org/latest_releases.html)

**Comment by xipki** [comment]
bcprov-jdk15发布到1.46版，之后就被bcprov-jdk15on代替了。2个jar的内容应该是差不多的，所以会有冲突。建议用最新版本的bcprov-jdk15on.
