### ISSUE TITLE
可以通过开发包建立SSL/TLS链接吗？

### ISSUE THREAD

**Issue by wzlu** [ZZMarquis/gmhelper#50]
如题

**Comment by ZZMarquis** [comment]
这个需要实现完整的SSL/TLS加密套件，目前这个项目在这个方面没有体现，可以直接参考一下BC库

**Comment by wzlu** [comment]
谢谢！我对BC库也不太熟悉，大概看了看，感觉也只实现了SM系列的算法。是不是也没有实现SSL/TLS的加密套件呢？

**Comment by ZZMarquis** [comment]
@wzlu 我看了下好像有了

**Comment by wzlu** [comment]
请问怎么看出来有了？抱歉，小白得很，没看到

**Comment by ZZMarquis** [comment]
@wzlu 啊。。。不好意思，我记错了，我去BC源码找了一下，应该是还没实现SSL/TLS加密套件

**Comment by wzlu** [comment]
谢谢！不过请问哪里可以找到已经实现得SSL/TLS套件么？我找了好几天也没找到，gmssl.cn貌似没有开源。

**Comment by ZZMarquis** [comment]
@wzlu 
gmssl开源的，它这个印象中是实现了，但是这个是基于OpenSSL的C语言项目哦
https://github.com/guanzhi/GmSSL

**Comment by wzlu** [comment]
是的，GmSSL实现了。但是我现在需要找一个java的，是不是没有啊？

**Comment by ZZMarquis** [comment]
我确实也没见过实现了的开源Java项目。GmSSL通过JNI提供了一套Java的接口，你看下有没有。

**Comment by wzlu** [comment]
谢谢！我看貌似是没有，demo里面也只是提供了算法部分。
