### ISSUE TITLE
请问BC库是否支持数字信封加解密呢？

### ISSUE THREAD

**Issue by FuchengDum** [ZZMarquis/gmhelper#52]
想请教下BC库是否支持数字信封(PKCS7）加解密呢？BC库中的PKCS7Padding的作用是什么呢？

**Comment by ZZMarquis** [comment]
PKCS7Padding就是对称加密中的一种Padding方式。跟数字信封不是一个东西。

**Comment by FuchengDum** [comment]
是的，查了相关资料发现PKCS7padding不是一个东西，BC库里面有支持PKCS7格式不带原文验签呢？之前提的数字信封加解密倒是解决了，现在想请教一下是否支持PKCS7格式不带原文这种方式验签

**Comment by ZZMarquis** [comment]
不带原文应该没法验签吧。验签中一个重要步骤就是验证签名中的HASH是否与原文生成的HASH值相同。

**Comment by FuchengDum** [comment]
已经解决了，感谢🙏
