### ISSUE TITLE
公钥对象和私钥对象转der编码的时候结果数据异常

### ISSUE THREAD

**Issue by Actor-Cl** [ZZMarquis/gmhelper#53]
der编码：
308201333081ec06072a8648ce3d02013081e0020101302c06072a8648ce3d0101022100fffffffeffffffffffffffffffffffffffffffff00000000ffffffffffffffff30440420fffffffeffffffffffffffffffffffffffffffff00000000fffffffffffffffc042028e9fa9e9d9f5e344d5a9e4bcf6509a7f39789f515ab8f92ddbcbd414d940e9304410432c4ae2c1f1981195f9904466a39c9948fe30bbff2660be1715a4589334c74c7bc3736a2f4f6779c59bdcee36b692153d0a9877cc62a474002df32e52139f0a0022100fffffffeffffffffffffffffffffffff7203df6b21c6052b53bbf40939d5412302010103420004088263b38f837c8fe9a239dc21f2ffd74e28f9cd4c16e01e7ad7c04b086f4f29fab1032c68cee6b97c5127aca62506594aa4162433bc16f3d5640cbe43953143

问题：der编码中间出现很多的f，百度结果时高位溢出，想知道你们出现这个问题了，时怎么解决的。

代码：
`KeyPair key = GMUtil.generateKeyPair();
						
						ECPrivateKeyParameters priKey =  BCECUtil.convertPrivateKeyToParameters((BCECPrivateKey)key.getPrivate());
						ECPublicKeyParameters pubKey = BCECUtil.convertPublicKeyToParameters((BCECPublicKey)key.getPublic());
						
						 System.out.println("Pri Hex:"+ ByteUtils.toHexString(priKey.getD().toByteArray()).toUpperCase());
						 System.out.println("Pub X Hex:"+ ByteUtils.toHexString(pubKey.getQ().getAffineXCoord().getEncoded()).toUpperCase());
						 System.out.println("Pub X Hex:"+ ByteUtils.toHexString(pubKey.getQ().getAffineYCoord().getEncoded()).toUpperCase());
						 System.out.println("Pub Point Hex:"+ ByteUtils.toHexString(pubKey.getQ().getEncoded(false)).toUpperCase());
						 
						 byte[] pubKeyX509Der = BCECUtil.convertECPublicKeyToX509(pubKey);
			             System.out.println("public key der length:" + pubKeyX509Der.length);
			             System.out.println("public key der:" + Hex.toHexString(pubKeyX509Der));`

**Comment by ZZMarquis** [comment]
没有问题，是这样的，SM2/ECC公钥的DER会把曲线参数也编码进去，而SM2的曲线参数里就是有连续的FF

**Comment by var33** [comment]
曲线参数是固定的，SM2/ECC公钥的DER会把曲线参数也编码进去，那么sm2密钥就都会出现连续的FF，可以一些密码设备生成密钥没有出现连续的FF，这个中间是做了什么处理吗？

**Comment by ZZMarquis** [comment]
那你要确认下这些密码设备生成的密钥的DER编码有没有把曲线参数编进去了，或者它们是编码了哪些参数进去。最简单的比较下长度，如果它们生成的公钥长度明显更短，那么可能就是没把曲线参数编进去。
