### ISSUE TITLE
sm2 加解密算法中 s及中文会丢失

### ISSUE THREAD

**Issue by dcldclll** [ZZMarquis/gmhelper#58]
![image](https://user-images.githubusercontent.com/25996156/131475982-52d5edd6-8c63-44e1-bd6b-d3c7406f67d2.png)

**Comment by dcldclll** [comment]
![image](https://user-images.githubusercontent.com/25996156/131476045-85501ce5-7ab3-4587-8b10-544962b92d92.png)

**Comment by ZZMarquis** [comment]
s丢失是因为s不是十六进制字符，十六进制字符是0123456789ABCDEF。这个是ByteUtils.toHexString转换的问题，它应该是把非十六进制字符字节跳过了。中文那个我猜应该也是类似问题吧。
