### ISSUE TITLE
Android上的问题

### ISSUE THREAD

**Issue by jeytin** [ZZMarquis/gmhelper#59]
String serverCerHexStr = response.getContent();
 X509Certificate x509Certificate = SM2CertUtil.getX509Certificate(Hex.decode(serverCerHexStr));
 BCECPublicKey bcecPublicKey = SM2CertUtil.getBCECPublicKey(x509Certificate);

类型转换报错：
java.lang.ClassCastException: com.android.org.conscrypt.X509PublicKey cannot be cast to org.bouncycastle.jce.interfaces.ECPublicKey

初始化调用也包异常
KeyPair midKP = SM2Util.generateKeyPair();

java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for KeyPairGenerator.EC.

Android是不是没法兼容使用 ？

**Comment by ZZMarquis** [comment]
#18

**Comment by jeytin** [comment]
```java 

 if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) != null) {
            double version = Security.getProvider(BouncyCastleProvider.PROVIDER_NAME).getVersion();
        }
        Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME);
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            Security.addProvider(new BouncyCastleProvider());
        }

```

初始化的时候加上版本冲突的判断可以正常运行
