### ISSUE TITLE
请教个sm4问题。

### ISSUE THREAD

**Issue by l42111996** [ZZMarquis/gmhelper#63]
我用java版本生成的加密后数据比c++版本的要长一段，这个可能是什么问题
输入 
0123456789abcdeffedcba98765432101122336789abcdeffedcba987633221123450000000000000000000000000000
key
byte[] key = { 0x01,0x23,0x45,0x67, (byte) 0x89, (byte) 0xab, (byte) 0xcd, (byte) 0xef, (byte) 0xfe, (byte) 0xdc, (byte) 0xba, (byte) 0x98,0x76,0x54,0x32,0x10 };
输出
681edf34d206965e86b3e94f536e424695f8e303d44b9af26df04779c6db54a8cf428d0ced3b19f34786e0d03cd021ff002a8a4efa863ccad024ac0300bb40d2

c版本输出为
681edf34d206965e86b3e94f536e424695f8e303d44b9af26df04779c6db54a8cf428d0ced3b19f34786e0d03cd021ff

**Comment by greenking19** [comment]
pkcs#7跟pkcs#5的却别

**Comment by ZZMarquis** [comment]
C++版本是哪个呢？

**Comment by l42111996** [comment]
我也不知道什么版本，不好的问题就把问题解决了，我让他把加密去掉了，不考虑了，感谢大佬
