### ISSUE TITLE
请问有.net版本吗

### ISSUE THREAD

**Issue by Alivan-P** [ZZMarquis/gmhelper#65]

**Comment by ZZMarquis** [comment]
我这个没有。BC库是有.net版本的，我这个其实也是基于BC的java版本的简单封装，.net的你可以基于BC自己做一下。
https://github.com/bcgit/bc-csharp

**Comment by lpilp** [comment]
https://github.com/hz281529512/SecretTes  可以在这个上修改修改， git上看了挺多.net版，基本都是用BC库的，但就这个最完整的，根据需要修改或是重新封装

**Comment by lpilp** [comment]
不好意思  是 https://github.com/hz281529512/SecretTest , 少打了一个t,

**Comment by Alivan-P** [comment]
@ZZMarquis @lpilp 好的，谢谢两位大佬。
