### ISSUE TITLE
你好，BCEUtil在生成非对称秘钥时，怎么转换为秘钥字节然后写配置。

### ISSUE THREAD

**Issue by csina99** [ZZMarquis/gmhelper#7]
你好，看了一下你的BCEUtil工具类，如果生成的是SM2非对称加密秘钥，怎么转化为字节形式或者字符串形式已配置项的方式存在呢，同时秘钥字节要还原为对应的秘钥。

**Comment by ZZMarquis** [comment]
代码里都有，Java密钥对象转DER字节流、DER字节流转Java密钥对象的方法都有。

**Comment by csina99** [comment]
嗯，看到了。顺便确认一下，对于国密的hmac算法，秘钥好像是随便输入的，不像国际开源算法Hmac需要通过keyGenerator生成指定格式的秘钥。

**Comment by ZZMarquis** [comment]
不是的。HMAC的KEY应该都是超过HASH结果长度的先做HASH，不足HASH结果长度的用0补齐。
