### ISSUE TITLE
SM4加密，第一次特别慢，有办法解决吗？

### ISSUE THREAD

**Issue by yanlun0323** [ZZMarquis/gmhelper#73]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/16319795/191708320-d53f3fe1-127c-45f0-80d1-955d1c2c9686.png">
应该是Cipher加载了什么，导致很慢，是我调用方式不对？
调用方法：SM4Util#encrypt_ECB_Padding
求大佬解答

**Comment by ZZMarquis** [comment]
感觉不太正常。方便的话，可以把你的代码贴上来看下。

**Comment by yanlun0323** [comment]
`public static byte[] encrypt_ECB_Padding(byte[] key, byte[] data)
            throws InvalidKeyException, NoSuchAlgorithmException, NoSuchProviderException,
            NoSuchPaddingException, IllegalBlockSizeException, BadPaddingException {
        Cipher cipher = generateECBCipher(ALGORITHM_NAME_ECB_PADDING, Cipher.ENCRYPT_MODE, key);
        return cipher.doFinal(data);
    }`

`private static Cipher generateECBCipher(String algorithmName, int mode, byte[] key)
            throws NoSuchAlgorithmException, NoSuchProviderException, NoSuchPaddingException,
            InvalidKeyException {
        Cipher cipher = Cipher.getInstance(algorithmName, BouncyCastleProvider.PROVIDER_NAME);
        Key sm4Key = new SecretKeySpec(key, ALGORITHM_NAME);
        cipher.init(mode, sm4Key);
        return cipher;
    }`

**Comment by ZZMarquis** [comment]
我没有复现到这个问题，我在SM4UtilTest里的测试代码里加了些耗时打印，在小数据量加密的情况下第一次也都是在是十几毫秒内完成的。所以不知道你的环境和代码是不是加了些别的逻辑。

**Comment by yanlun0323** [comment]
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/16319795/223046762-2736f976-6515-4772-98b8-98172fc0dc87.png">
这里的test案例，耗时部分初始化已经完成了吧，所以耗时计算看不出来。
我这里的案例是直接指定了Key，然后初次加载很慢，直接放static代码块初始化也没用。。
<img width="976" alt="image" src="https://user-images.githubusercontent.com/16319795/223047007-9647e589-03db-408c-a6d4-32f3c0d5e57e.png">

**Comment by ZZMarquis** [comment]
方便的话，可以把完整的代码贴一下。我测试、调试看看。

**Comment by ZZMarquis** [comment]
看下你遇到的问题是不是跟这个类似：https://toutiao.io/posts/i02ux77

**Comment by yanlun0323** [comment]
> 

今天也看到了这篇文章，应该是初始化加载太慢了。Cipher.getInstance初次太耗时了

**Comment by freenet-233** [comment]
把hex改成转base64

**Comment by chenjy952-droid** [comment]
> <img alt="image" width="382" src="https://user-images.githubusercontent.com/16319795/191708320-d53f3fe1-127c-45f0-80d1-955d1c2c9686.png">
> 
> 应该是Cipher加载了什么，导致很慢，是我调用方式不对？ 调用方法：SM4Util#encrypt_ECB_Padding 求大佬解答

第一次加密要先初始化Cipher，比较耗时。可以在项目启动时先初始化或者先调用一次方法
