### ISSUE TITLE
关于国密算法SM2加密问题，使用老版本的bcprov包改造加密实现，渠道接入无法解密，求解答

### ISSUE THREAD

**Issue by yanlun0323** [ZZMarquis/gmhelper#74]
国密改造提供了SDK包，但是与我目前底层的不一致，该底层涉及到多个项目，如果涉及到底层改动，比较麻烦。刚开始想着选择利用maven-shade重新打包，让两个版本并存，不曾想jdk对这一类型provider做了签名校验，任务失败。。。
然后想着改造上游提供的sdk（有源码），改成老版本的类实现，虽然能加密，签名能够，但是经过测试，是SM2加密的问题，长度什么的好像也没问题，不知道大佬有没有遇到过这个问题。
现在两种方案都行不通，那么就只能改造底层类，copy了大佬的实现，升级到1.67（原版本是jdk16-1.46版本，相当古老了），这次改造很顺利，一个下午解决了所遇到的问题，但是不太明白，究竟为何，希望大佬解答。

**Comment by ZZMarquis** [comment]
看看是不是密文C1C3C2排序的问题，确认应该是C1C3C2还是C1C2C3

**Comment by yanlun0323** [comment]
同样的实现，其他上游验签能通过，是不是有padding之类的区别（或者签名原串处理方式不一样、userId不一样），这个就不太清楚了，密文顺序我调整过，没有奏效，谢谢大佬！
