### ISSUE TITLE
这个与gmssl签名能互通吗？·

### ISSUE THREAD

**Issue by ugenehan** [ZZMarquis/gmhelper#79]
用这个和gmssl的sm2_sign与sm2_verify不能互通，是用的不对吗？

**Comment by ZZMarquis** [comment]
之前和gmssl2.x之间是测试过没问题的。gmssl3.x暂时没有测试过。
SM2签名验签要确认：
1、公私钥是确实是一对的
2、withID是相同的

**Comment by ugenehan** [comment]
> 之前和gmssl2.x之间是测试过没问题的。gmssl3.x暂时没有测试过。 SM2签名验签要确认： 1、公私钥是确实是一对的 2、withID是相同的

已解决。
